services:
  db:
    image: 'postgres:18.3-alpine'
    environment:
      - 'POSTGRES_DB=egidedb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgam_user -d sgam_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: egide_app
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/egidedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  pgdata:
