server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5434/egidedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.validate-on-migrate=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

security.jwt.secret=egide-ia-super-secreto-com-mais-de-32-caracteres-123456
security.jwt.expiration-ms=86400000 

ai.base-url=http://localhost:8000/api/v1
ai.api-key=${EGIDE_IA_MS_API_KEY:chave_secreta_egide}
ai.connect-timeout-ms=50000
ai.read-timeout-ms=300000
