ALTER TABLE report
    ADD COLUMN IF NOT EXISTS ouvidor_id BIGINT;

ALTER TABLE report
    DROP CONSTRAINT IF EXISTS fk_report_ouvidor;
ALTER TABLE report
    ADD CONSTRAINT fk_report_ouvidor FOREIGN KEY (ouvidor_id) REFERENCES user_info (id);

CREATE INDEX IF NOT EXISTS idx_report_ouvidor_id ON report (ouvidor_id);

DROP TABLE IF EXISTS report_response;

CREATE TABLE preliminary_report (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active               BOOLEAN DEFAULT TRUE,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    report_id            BIGINT NOT NULL UNIQUE,
    ouvidor_id           BIGINT NOT NULL,
    decision             VARCHAR(64) NOT NULL,
    justification        TEXT,
    penalty_type         VARCHAR(32),
    penalty_description  TEXT,
    ai_suggestion        TEXT,
    used_ai_suggestion   BOOLEAN DEFAULT FALSE,
    submitted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_preliminary_report PRIMARY KEY (id),
    CONSTRAINT fk_preliminary_report_report   FOREIGN KEY (report_id)   REFERENCES report    (id),
    CONSTRAINT fk_preliminary_report_ouvidor  FOREIGN KEY (ouvidor_id)  REFERENCES user_info (id)
);

CREATE INDEX idx_preliminary_report_ouvidor   ON preliminary_report (ouvidor_id);
CREATE INDEX idx_preliminary_report_decision  ON preliminary_report (decision);

CREATE TABLE proof_observation (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active                 BOOLEAN DEFAULT TRUE,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    file_id                BIGINT NOT NULL,
    preliminary_report_id  BIGINT,
    ouvidor_id             BIGINT NOT NULL,
    observation            TEXT NOT NULL,
    CONSTRAINT pk_proof_observation PRIMARY KEY (id),
    CONSTRAINT fk_proof_observation_file        FOREIGN KEY (file_id)               REFERENCES file              (id),
    CONSTRAINT fk_proof_observation_preliminary FOREIGN KEY (preliminary_report_id) REFERENCES preliminary_report (id) ON DELETE SET NULL,
    CONSTRAINT fk_proof_observation_ouvidor     FOREIGN KEY (ouvidor_id)            REFERENCES user_info          (id)
);

CREATE INDEX idx_proof_observation_file        ON proof_observation (file_id);
CREATE INDEX idx_proof_observation_preliminary ON proof_observation (preliminary_report_id);
CREATE INDEX idx_proof_observation_ouvidor     ON proof_observation (ouvidor_id);
