ALTER TABLE report ADD COLUMN IF NOT EXISTS denunciado_user_id BIGINT;

ALTER TABLE report
    DROP CONSTRAINT IF EXISTS fk_report_denunciado;
ALTER TABLE report
    ADD CONSTRAINT fk_report_denunciado FOREIGN KEY (denunciado_user_id) REFERENCES user_info (id);

CREATE INDEX IF NOT EXISTS idx_report_denunciado_user_id ON report (denunciado_user_id);

ALTER TABLE report ADD COLUMN IF NOT EXISTS repass_count INT NOT NULL DEFAULT 0;

CREATE TABLE final_report (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active               BOOLEAN DEFAULT TRUE,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    report_id            BIGINT NOT NULL UNIQUE,
    ouvidor_id           BIGINT NOT NULL,
    defense_id           BIGINT,
    decision             VARCHAR(64) NOT NULL,
    justification        TEXT,
    penalty_type         VARCHAR(32),
    penalty_description  TEXT,
    submitted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_final_report PRIMARY KEY (id),
    CONSTRAINT fk_final_report_report  FOREIGN KEY (report_id)  REFERENCES report    (id),
    CONSTRAINT fk_final_report_ouvidor FOREIGN KEY (ouvidor_id) REFERENCES user_info (id)
);

CREATE INDEX idx_final_report_report_id ON final_report (report_id);

CREATE TABLE appeal (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active              BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    report_id           BIGINT NOT NULL,
    appellant_user_id   BIGINT NOT NULL,
    appellant_role      VARCHAR(32) NOT NULL,
    grounds             TEXT,
    new_ouvidor_id      BIGINT,
    status              VARCHAR(32) NOT NULL,
    submitted_at        TIMESTAMP WITHOUT TIME ZONE,
    closed_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appeal PRIMARY KEY (id),
    CONSTRAINT fk_appeal_report      FOREIGN KEY (report_id)         REFERENCES report    (id),
    CONSTRAINT fk_appeal_appellant   FOREIGN KEY (appellant_user_id) REFERENCES user_info (id),
    CONSTRAINT fk_appeal_new_ouvidor FOREIGN KEY (new_ouvidor_id)    REFERENCES user_info (id),
    CONSTRAINT uq_appeal_per_role    UNIQUE (report_id, appellant_role)
);

CREATE INDEX idx_appeal_report_id      ON appeal (report_id);
CREATE INDEX idx_appeal_new_ouvidor_id ON appeal (new_ouvidor_id);

ALTER TABLE file ADD COLUMN IF NOT EXISTS appeal_id BIGINT;
ALTER TABLE file
    DROP CONSTRAINT IF EXISTS fk_file_appeal;
ALTER TABLE file
    ADD CONSTRAINT fk_file_appeal FOREIGN KEY (appeal_id) REFERENCES appeal (id);

CREATE INDEX IF NOT EXISTS idx_file_appeal_id ON file (appeal_id);

CREATE TABLE appeal_report (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active               BOOLEAN DEFAULT TRUE,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    report_id            BIGINT NOT NULL UNIQUE,
    new_ouvidor_id       BIGINT NOT NULL,
    decision             VARCHAR(64) NOT NULL,
    justification        TEXT,
    penalty_type         VARCHAR(32),
    penalty_description  TEXT,
    submitted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appeal_report PRIMARY KEY (id),
    CONSTRAINT fk_appeal_report_report       FOREIGN KEY (report_id)      REFERENCES report    (id),
    CONSTRAINT fk_appeal_report_new_ouvidor  FOREIGN KEY (new_ouvidor_id) REFERENCES user_info (id)
);

CREATE INDEX idx_appeal_report_report_id ON appeal_report (report_id);

CREATE TABLE general_validation (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active                        BOOLEAN DEFAULT TRUE,
    created_at                    TIMESTAMP WITHOUT TIME ZONE,
    updated_at                    TIMESTAMP WITHOUT TIME ZONE,
    report_id                     BIGINT NOT NULL,
    final_report_id               BIGINT,
    appeal_report_id              BIGINT,
    ouvidor_geral_id              BIGINT NOT NULL,
    action                        VARCHAR(32) NOT NULL,
    altered_decision              VARCHAR(64),
    altered_justification         TEXT,
    altered_penalty_type          VARCHAR(32),
    altered_penalty_description   TEXT,
    repass_new_ouvidor_id         BIGINT,
    decided_at                    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_general_validation PRIMARY KEY (id),
    CONSTRAINT fk_general_validation_report          FOREIGN KEY (report_id)          REFERENCES report        (id),
    CONSTRAINT fk_general_validation_final_report    FOREIGN KEY (final_report_id)    REFERENCES final_report  (id),
    CONSTRAINT fk_general_validation_appeal_report   FOREIGN KEY (appeal_report_id)   REFERENCES appeal_report (id),
    CONSTRAINT fk_general_validation_ouvidor_geral   FOREIGN KEY (ouvidor_geral_id)   REFERENCES user_info     (id),
    CONSTRAINT fk_general_validation_repass_ouvidor  FOREIGN KEY (repass_new_ouvidor_id) REFERENCES user_info  (id)
);

CREATE INDEX idx_general_validation_report_id        ON general_validation (report_id);
CREATE INDEX idx_general_validation_ouvidor_geral_id ON general_validation (ouvidor_geral_id);
