ALTER TABLE report
    ADD COLUMN IF NOT EXISTS phase3_notified_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS defense (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active               BOOLEAN DEFAULT TRUE,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    defense_text         TEXT,
    submitted_at         TIMESTAMP WITHOUT TIME ZONE,
    submitted_by_user_id BIGINT NOT NULL,
    report_id            BIGINT NOT NULL UNIQUE,
    CONSTRAINT pk_defense PRIMARY KEY (id),
    CONSTRAINT fk_defense_report FOREIGN KEY (report_id) REFERENCES report (id),
    CONSTRAINT fk_defense_submitted_by FOREIGN KEY (submitted_by_user_id) REFERENCES user_info (id)
);

ALTER TABLE file
    ADD COLUMN IF NOT EXISTS defense_id BIGINT;

ALTER TABLE file
    DROP CONSTRAINT IF EXISTS fk_file_defense;
ALTER TABLE file
    ADD CONSTRAINT fk_file_defense FOREIGN KEY (defense_id) REFERENCES defense (id);

CREATE INDEX IF NOT EXISTS idx_file_defense_id ON file (defense_id);
