CREATE TABLE IF NOT EXISTS notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active            BOOLEAN DEFAULT TRUE,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    recipient_user_id BIGINT NOT NULL,
    report_id         BIGINT,
    type              VARCHAR(64) NOT NULL,
    title             VARCHAR(255) NOT NULL,
    message           TEXT,
    read_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_user_id) REFERENCES user_info (id),
    CONSTRAINT fk_notification_report FOREIGN KEY (report_id) REFERENCES report (id)
);

CREATE INDEX IF NOT EXISTS idx_notification_recipient_user_id ON notification (recipient_user_id);
CREATE INDEX IF NOT EXISTS idx_notification_recipient_read_at ON notification (recipient_user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_notification_created_at ON notification (created_at);
