CREATE TABLE user_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active     BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255),
    name       VARCHAR(255),
    username   VARCHAR(255),
    password   VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_userinfo PRIMARY KEY (id)
);