CREATE TABLE report_ai_analysed (
                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        report_id    BIGINT NOT NULL,
                        active     BOOLEAN,
                        created_at TIMESTAMP WITHOUT TIME ZONE,
                        updated_at TIMESTAMP WITHOUT TIME ZONE,
                        title_anonymized      VARCHAR(255) NOT NULL,
                        description_anonymized TEXT NOT NULL,
                        category VARCHAR(50),
                        has_conflict BOOLEAN,

                        CONSTRAINT pk_report_ai_analysed PRIMARY KEY (id),
                        CONSTRAINT fk_report_ai_report FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE
);