CREATE TABLE report_ai_analysed (
                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        report_id    BIGINT NOT NULL,
                        created_at TIMESTAMP WITHOUT TIME ZONE,
                        updated_at TIMESTAMP WITHOUT TIME ZONE,
                        title      VARCHAR(255) NOT NULL,
                        description TEXT NOT NULL,

                        CONSTRAINT pk_report_ai_analysed PRIMARY KEY (id),
                        CONSTRAINT fk_report_ai_report FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE
);