CREATE TABLE department (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active     BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    acronym    VARCHAR(255),
    CONSTRAINT pk_department PRIMARY KEY (id)
);

ALTER TABLE user_info
    ADD COLUMN department_id BIGINT;

ALTER TABLE user_info
    ADD CONSTRAINT fk_user_info_department FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE report
    ADD COLUMN protocol_number VARCHAR(255),
    ADD COLUMN date_of_occurrence DATE,
    ADD COLUMN user_info_id BIGINT;

ALTER TABLE report
    ADD CONSTRAINT fk_report_user_info FOREIGN KEY (user_info_id) REFERENCES user_info (id);

CREATE TABLE report_processed (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active       BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    title_anonymized        VARCHAR(255),
    description_anonymized  TEXT,
    category     VARCHAR(50),
    status       VARCHAR(50),
    has_conflict BOOLEAN,
    report_id    BIGINT UNIQUE,
    CONSTRAINT pk_report_processed PRIMARY KEY (id)
);

ALTER TABLE report_processed
    ADD CONSTRAINT fk_report_processed_report FOREIGN KEY (report_id) REFERENCES report (id);
