CREATE TABLE report_response (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active            BOOLEAN DEFAULT TRUE,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    response_text     TEXT,
    ai_suggestion     TEXT,
    used_ai_suggestion BOOLEAN,
    responded_at      TIMESTAMP WITHOUT TIME ZONE,
    report_id         BIGINT UNIQUE,
    CONSTRAINT pk_report_response PRIMARY KEY (id)
);

ALTER TABLE report_response
    ADD CONSTRAINT fk_report_response_report FOREIGN KEY (report_id) REFERENCES report (id);
